# Generated by scripts/render-tap.sh. DO NOT EDIT.
cask "agent-firehose" do
  version "0.1.3"

  on_arm do
    sha256 "6ef5a40a230012ce03d65c5798dd45436a54190b7e1537ef06be88cfbce0ae79"

    url "https://github.com/treetopdevs/llm-firehose/releases/download/v#{version}/agent-firehose_#{version}_aarch64.dmg"
  end
  on_intel do
    sha256 "386f57f950a52b9782fe88fc8891862137d004fd67073bc271711e970dfee002"

    url "https://github.com/treetopdevs/llm-firehose/releases/download/v#{version}/agent-firehose_#{version}_x86_64.dmg"
  end

  name "Agent Firehose"
  desc "Live, local-first timeline of what AI coding agents are doing on your machine"
  homepage "https://github.com/treetopdevs/llm-firehose"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on :macos

  app "Agent Firehose.app"

  # Not signed/notarized yet, so Gatekeeper blocks the first launch. The cask
  # does not strip the quarantine flag on the user's behalf; caveats explain
  # the one-time approval instead.
  caveats <<~EOS
    Agent Firehose is not yet signed or notarized, so macOS blocks the first launch.
    Approve it once in System Settings > Privacy & Security ("Open Anyway"), or run:
      xattr -dr com.apple.quarantine "/Applications/Agent Firehose.app"
  EOS

  # Deliberately no zap for ~/.agentfirehose: it holds the user's event spool.
end
