# Generated by scripts/render-tap.sh. DO NOT EDIT.
cask "agent-firehose" do
  version "0.2.0"

  on_arm do
    sha256 "43fbc1560ec9bfe4934d266d3ac4098cd43b9bf5c6e5fb7e10f74f9121d10e50"

    url "https://github.com/treetopdevs/llm-firehose/releases/download/v#{version}/agent-firehose_#{version}_aarch64.dmg"
  end
  on_intel do
    sha256 "130a335388380a02c502b35f5b0bc1436441faa095637a863c77780adcafb14e"

    url "https://github.com/treetopdevs/llm-firehose/releases/download/v#{version}/agent-firehose_#{version}_x86_64.dmg"
  end

  name "Agent Firehose"
  desc "Live, local-first timeline of what AI coding agents are doing on your machine"
  homepage "https://github.com/treetopdevs/llm-firehose"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on :macos

  app "Agent Firehose.app"

  # Not signed/notarized yet, so Gatekeeper blocks the first launch. The cask
  # does not strip the quarantine flag on the user's behalf; caveats explain
  # the one-time approval instead.
  caveats <<~EOS
    Agent Firehose is not yet signed or notarized, so macOS blocks the first launch.
    Approve it once in System Settings > Privacy & Security ("Open Anyway"), or run:
      xattr -dr com.apple.quarantine "/Applications/Agent Firehose.app"
  EOS

  # Deliberately no zap for ~/.agentfirehose: it holds the user's event spool.
end
