# This file was generated by GoReleaser. DO NOT EDIT.
cask "firehose" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "eecd7194786b7e74ea6e1b46233d11a218ac6fe27ed90de56d0e57711be71d8a"
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v#{version}/firehose_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "621a9ebcae799fd23afcc0659018f913aa04fcfae8fd5328a074107e20c1a719"
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v#{version}/firehose_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dec53bc5669f78e36835b6150e3cca2b50981a3df24b9a65b7a4d5708e0e70ba"
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v#{version}/firehose_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4ee3515c2ae057cbb6b0323cfcb49f23a07ed5c1d14e78793382138501417f9d"
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v#{version}/firehose_#{version}_linux_amd64.tar.gz"
    end
  end

  name "firehose"
  desc "Live, local-first timeline of what AI coding agents are doing on your machine"
  homepage "https://github.com/treetopdevs/llm-firehose"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "firehose"
  binary "firehosed"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/firehose"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/firehosed"]
    end
  end

  # No zap stanza required
end
