# This file was generated by GoReleaser. DO NOT EDIT.
cask "firehose" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "b2ffcbcb4ace0c91b1ff390bb52f3f219d612b617fe7fa93097cc8d78c4dfe56"
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v#{version}/firehose_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e699919625367973610622bf33c8e4ffdd65d946bb785edae6824e6cd243ff3a"
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v#{version}/firehose_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "90c51eb6f859e65b45715cb40a726829bba435744855143606f39b176f1fe95c"
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v#{version}/firehose_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "42fa006703cea26a15a9c76a3fd73acc9e380c4b1560f98c6db437c9783af033"
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v#{version}/firehose_#{version}_linux_amd64.tar.gz"
    end
  end

  name "firehose"
  desc "Live, local-first timeline of what AI coding agents are doing on your machine"
  homepage "https://github.com/treetopdevs/llm-firehose"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "firehose"
  binary "firehosed"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/firehose"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/firehosed"]
    end
  end

  # No zap stanza required
end
