# This file was generated by GoReleaser. DO NOT EDIT.
cask "firehose" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "d9d67e42eeed5a7d7de32d8d9c319b4d6ee0c60d3ec3b05397759433dfd9196c"
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v#{version}/firehose_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b5a2dc2106623ec79087695bedc4672fde15744e5a490fdb9f387e0ea8fe4483"
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v#{version}/firehose_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a412aa21d23123c61495255590cb356fcd2b657e808649751120d688acbc7bea"
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v#{version}/firehose_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d2cb911d16ba9aeadcf3cbd4bfb15f15941e229a35bca057406c5d0bc7cc7782"
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v#{version}/firehose_#{version}_linux_amd64.tar.gz"
    end
  end

  name "firehose"
  desc "Live, local-first timeline of what AI coding agents are doing on your machine"
  homepage "https://github.com/treetopdevs/llm-firehose"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "firehose"
  binary "firehosed"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/firehose"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/firehosed"]
    end
  end

  # No zap stanza required
end
