# Generated by scripts/render-tap.sh. DO NOT EDIT.
class Firehose < Formula
  desc "Live, local-first timeline of what AI coding agents are doing on your machine"
  homepage "https://github.com/treetopdevs/llm-firehose"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v0.2.0/firehose_0.2.0_darwin_arm64.tar.gz"
      sha256 "95503b86faf7d903d2df8cbcf7c7e6512972991dc57b15b2658e4f5840ad6241"
    end
    on_intel do
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v0.2.0/firehose_0.2.0_darwin_amd64.tar.gz"
      sha256 "74c7ad2eec6a69cfccfa811d227412751e2816200f3f8237e09979d9fbba3ea4"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v0.2.0/firehose_0.2.0_linux_arm64.tar.gz"
      sha256 "ca27b66c156e90e653ea93bcbc01259315338048dd7c5546d9cfd0b8806bfd96"
    end
    on_intel do
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v0.2.0/firehose_0.2.0_linux_amd64.tar.gz"
      sha256 "b8dc3291e28a36bc96a32491b2a5937fc39490e0c13c9be93431390add21673c"
    end
  end

  def install
    bin.install "firehose"
    bin.install "firehosed"
  end

  service do
    run [opt_bin/"firehosed"]
    keep_alive true
    log_path var/"log/firehosed.log"
    error_log_path var/"log/firehosed.log"
  end

  def caveats
    <<~EOS
      Run the capture daemon in the background (and at login):
        brew services start firehose
      Then wire up the agents you use, e.g.:
        firehose install claude-code
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/firehose version")
    assert_match version.to_s, shell_output("#{bin}/firehosed --version")
  end
end
