# Generated by scripts/render-tap.sh. DO NOT EDIT.
class Firehose < Formula
  desc "Live, local-first timeline of what AI coding agents are doing on your machine"
  homepage "https://github.com/treetopdevs/llm-firehose"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v0.1.3/firehose_0.1.3_darwin_arm64.tar.gz"
      sha256 "75ad25cd2ced4390ba02571c1eec24bc16fc176debb045d495f8a2d47512d2ce"
    end
    on_intel do
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v0.1.3/firehose_0.1.3_darwin_amd64.tar.gz"
      sha256 "379224759e1c785c870c6b2769a01b3529e02b85da5fe20d42050aeab30fb4c9"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v0.1.3/firehose_0.1.3_linux_arm64.tar.gz"
      sha256 "aa32bea5d8ebe1df04b4cd69e202bcc47444c1c68d408f5e12846c5d894c2f6f"
    end
    on_intel do
      url "https://github.com/treetopdevs/llm-firehose/releases/download/v0.1.3/firehose_0.1.3_linux_amd64.tar.gz"
      sha256 "60d56e00b7aa09dff3568f73760306ea19307f3c6651649f845a727298db4789"
    end
  end

  def install
    bin.install "firehose"
    bin.install "firehosed"
  end

  service do
    run [opt_bin/"firehosed"]
    keep_alive true
    log_path var/"log/firehosed.log"
    error_log_path var/"log/firehosed.log"
  end

  def caveats
    <<~EOS
      Run the capture daemon in the background (and at login):
        brew services start firehose
      Then wire up the agents you use, e.g.:
        firehose install claude-code
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/firehose version")
    assert_match version.to_s, shell_output("#{bin}/firehosed --version")
  end
end
